src/objects/Aobject__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Aobject</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Aobject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aobjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bobject__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Bobject</label>
    <nameField>
        <displayFormat>B-{00}</displayFormat>
        <label>Bobject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bobjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cobject__c.object
<CustomObject>
    <fields>
        <fullName>Aobject_MD__c</fullName>
        <label>Aobject MD</label>
        <referenceTo>Aobject__c</referenceTo>
        <relationshipLabel>Cobjects</relationshipLabel>
        <relationshipName>Cobjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bobject_MD__c</fullName>
        <label>Bobject MD</label>
        <referenceTo>Bobject__c</referenceTo>
        <relationshipLabel>Cobjects</relationshipLabel>
        <relationshipName>Cobjects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Cobject</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>Cobject Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cobjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelationshipQueryClass.cls
public with sharing class RelationshipQueryClass{

//This method retrieves all tha accounts of the active contacts belonging to 'Media' industry
    public static List<Contact> ActiveMediaContactAccounts(){
        return [SELECT ID
                     , Account.Name
                     , Account.Industry 
                  FROM Contact 
                 WHERE Account.Active__c
                    IN ('Yes') 
                   AND Account.Industry 
                    IN ('Media')];
    }
    
//This method retrieves all records of 'C' with name 'John' along with parent details.
    public static List<Cobject__c> CObjectParentDetails(String searchName){
        return [SELECT ID
                     , Name
                     , Name__C
                     , Aobject_MD__r.ID
                     , Aobject_MD__r.Name
                     , Aobject_MD__r.Name__c
                     , Bobject_MD__r.ID
                     , Bobject_MD__r.Name
                     , Bobject_MD__r.Name__c 
                  FROM Cobject__c 
                 WHERE Name__c=:searchName];
    }
   
//This method finds all associated contact records of the Account which contains the word 'John'.    
    public static List<Account> AccountHavingJohnContacts(){
        return [select Id
                     , Name
                     , 
               (SELECT Id
                     , Name
                     , AccountId 
                  FROM Contacts) 
                  FROM Account 
                 WHERE Name 
                  LIKE '%john%' ];
    }
//This method finds all Account records which have at least an opportunity record which is 'Closed Won'
    public static List<Account> AtLeastOneOpporunityAccount(){
        return [SELECT Id
                     ,
               (SELECT AccountId 
                  FROM Opportunities 
                 WHERE StageName 
                    IN ('Closed Won')) 
                  FROM Account];
    } 
//This method retrieves all parents with all their child records where in child name is 'John' querying on 'A'.
    public static List<Aobject__c> ParentChildParentRecords(){
        return [select Id,Name__c, (SELECT Id
                                         , Name__c
                                         , Bobject_MD__r.ID
                                         , Bobject_MD__r.Name
                                         , Bobject_MD__r.Name__c 
                                      FROM Cobjects__r 
                                     WHERE Name__c 
                                      LIKE 'John') 
                                      FROM Aobject__c];
    }
}