src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>New_Client__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <label>Invoice Line Item</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labour_Hours__c</fullName>
        <label>Labour Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Fee__c</fullName>
        <label>Service Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateInvoicePageExtensionTestClass.cls
//This is the testclass for GenerateInvoicePageExtension
@isTest
public class GenerateInvoicePageExtensionTestClass{
    //This testmethod tests the default entry records of Line Item and Invoice.
    static testmethod void getInvoiceData(){
        Account objAccount=new Account(Name='Anjali');
        insert objAccount;
        Contact objContact=new Contact(LastName='Patel');
        insert objContact;
        Invoice__c objInvoice=new Invoice__c(New_Client__c=true,Related_Account__c=objAccount.Id,Related_Contact__c=objContact.Id);
        insert objInvoice;
        List<Line_Item__c> LineItemList=new List<Line_Item__c>();
        Line_Item__c objLineItem1=new Line_Item__c(Item_Name__c='abc',Labour_Hours__c=4,Service_Fee__c=500,Invoice_Line_Item__c=objInvoice.Id);
        Line_Item__c objLineItem2=new Line_Item__c(Item_Name__c='xyz',Labour_Hours__c=2,Service_Fee__c=1500,Invoice_Line_Item__c=objInvoice.Id);
        LineItemList.add(objLineItem1); 
        LineItemList.add(objLineItem2); 
        insert LineItemList;
       // ApexPages.currentPage().getParameters().put('id',objInvoice.Id);
        ApexPages.StandardController sc;
        Test.startTest();
        GenerateInvoicePageExtension objPage=new GenerateInvoicePageExtension(sc);
        Test.setCurrentPageReference(new PageReference('Page.GenerateInvoicePage'));
        System.currentPageReference().getParameters().put('id',objInvoice.Id);
        Test.stopTest();
    }
    
}