src/objects/Language__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This list setting specifies the language and its code</description>
    <fields>
        <fullName>Language_Code__c</fullName>
        <inlineHelpText>It is the code of the related language.</inlineHelpText>
        <label>Language Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language</label>
</CustomObject>

src/classes/StudentRegistrationPageExtension.cls
public class StudentRegistrationPageExtension{
    private ApexPages.StandardController sc;
    public String languageCode {get;set;}
    public Boolean messageRender {get;set;}
        
    public StudentRegistrationPageExtension(ApexPages.StandardController sc){
        this.sc=sc;
        messageRender=false;
    }
    
    public List<SelectOption> getLanguageList(){
        List<SelectOption> languagePickValue=new List<SelectOption>();
        Map<String,Language__c> LanguageCustomSettingMap=Language__c.getAll();
        List<String> LanguageList=new List<String>();
        LanguageList.addAll(LanguageCustomSettingMap.keySet());
        LanguageList.sort();
        for(String LanguageName: LanguageList){
           languagePickValue.add(new SelectOption(LanguageCustomSettingMap.get(LanguageName).Language_Code__c,LanguageName)); 
        }
        return languagePickValue; 
    }
    
    public pageReference save(){
        sc.save();
        messageRender=true;
        return null;
    }
}