src/objects/Language__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This list setting specifies the language and its code</description>
    <fields>
        <fullName>Language_Code__c</fullName>
        <inlineHelpText>It is the code of the related language.</inlineHelpText>
        <label>Language Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language</label>
</CustomObject>

src/classes/CustomTextManipulationPageController.cls
public class CustomTextManipulationPageController{
    public String languageCode {get;set;}
    
    public CustomTextManipulationPageController(){
    }
    
    public List<SelectOption> getLanguageList(){
        List<SelectOption> languagePickValue=new List<SelectOption>();
        Map<String,Language__c> LanguageCustomSettingMap=Language__c.getAll();
        List<String> LanguageList=new List<String>();
        LanguageList.addAll(LanguageCustomSettingMap.keySet());
        LanguageList.sort();
        for(String LanguageName: LanguageList){
           languagePickValue.add(new SelectOption(LanguageCustomSettingMap.get(LanguageName).Language_Code__c,LanguageName)); 
        }
        return languagePickValue; 
    }
}