src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <label>Invoice Line Item</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labour_Cost__c</fullName>
        <formula>Labour_Hours__c  * 75</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field calculates labour cost according to the no. of labour hours.</inlineHelpText>
        <label>Labour Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Fee__c</fullName>
        <label>Service Fee</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>IF( Invoice_Line_Item__r.New_Client__c , 
             ( Labour_Cost__c  +  Service_Fee__c  - 50) * (4.25 / 100),
             ( Labour_Cost__c  +  Service_Fee__c ) * (4.25 / 100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Service_Fee__c  +  Labour_Cost__c  +  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateInvoicePageExtension.cls
public class GenerateInvoicePageExtension{

    ApexPages.StandardController sc;
    public String invoiceID {get;set;}
    public List<Line_Item__c> relatedLineItemList=new List<Line_Item__c>();
    public Double totalBillAmount {get;set;}
     
    public GenerateInvoicePageExtension( ApexPages.StandardController sc){
        invoiceID=ApexPages.currentPage().getParameters().get('id');     
    } 
    
    public List<Line_Item__c> getRelatedLineItemList(){
        return [SELECT Id
                     , Invoice_Line_Item__c
                     , Item_Name__c
                     , Labour_Cost__c
                     , Service_Fee__c
                     , Tax__c
                     , Total_Amount__c 
                  FROM Line_Item__c 
                 WHERE Invoice_Line_Item__c=:invoiceID];
    }
    
    public Double getTotalBillAmount(){
      /*  AggregateResult[] objSum=[select sum(Total_Amount__c) billTotal from Line_Item__c where Invoice_Line_Item__c=:invoiceID GROUP BY Invoice_Line_Item__c];
        system.debug(objSum[0]);
        system.debug((Double)objSum[0].get('billTotal'));
        return (Double)objSum[0].get('billTotal');*/
        Double billAmount;
        for(Line_Item__c objLineItem: relatedLineItemList){
            billAmount+= objLineItem.Total_Amount__c ;
            system.debug(billAmount);
        }
        return billAmount;
    }
}